config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :users

  root 'landing#index'

  get 'landing/' => 'landing#index'

  get '/login', to:"login#login"

  get 'subjects' => 'subjects#index'
  get 'courses' => 'courses#index'
  get 'instructors' => 'instructors#index'
  get 'search' => 'search#index'
  get 'do_search' => 'search#do_search', defaults: { format: 'js' }
  get 'searchresult' => 'search#result'
  get 'do_search' => 'search#do_search'

  resources :instructors
  resources :courses
  resources :subjects
  resources :enrollments

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  protect_from_forgery except: :do_search
  #????????

  def index
    @courses = Course.all.map {|c| [c.subject_id, c.id]}
    @courses = [["All", 0]] + @courses
  end

  def do_search
    @courses = Course.search(params)

    respond_to do |format|
      format.js
    end

  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_result.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Enroll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.subject_id %></td>
        <td><%= link_to 'Enroll', enrollments_path(course_id: "#{course.subject_id}", user_id: "#{current_user.id}"), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/search/do_search.js.erb
$("#search_results").html("<%= escape_javascript(render(partial: 'result')) %>");

app/views/search/index.html.erb
<div>
  <h1>Search</h1>
  <%= form_tag do_search_path, :method => 'get', :remote => true, :id => "search" do %>
    <p>
      <label> Key Words </label>
      <%= text_field_tag :keywords, params[:keywords] %>
      <label> Subject </label>
      <%= select_tag "subject_id", options_for_select(@courses) %>
      <!-- <%= text_field_tag :subject, params[:subject] %> -->
      <!-- AND HOW DOES IT WORK??? -->
      <!-- <%= submit_tag "Search", :name => nil %> -->
    </p>
  <% end %>
</div>

<div>
  <div id="search_results">
</div>

app/views/search/result.html.erb
<h1>Search Results</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Enroll</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.subject_id %></td>
        <td><%= link_to 'Enroll', enrollments_path(course_id: "#{course.subject_id}", user_id: "#{current_user.id}"), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>